FROM golang:1.25.2 AS base
# Needed for ca-certs

FROM scratch

COPY --from=base /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY ztoperator /ztoperator
USER 65532:65532
ENTRYPOINT ["/ztoperator"]