# permissions for end users to view authpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ztoperator
    app.kubernetes.io/managed-by: kustomize
  name: authpolicy-viewer-role
rules:
- apiGroups:
  - ztoperator.kartverket.no
  resources:
  - authpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ztoperator.kartverket.no
  resources:
  - authpolicies/status
  verbs:
  - get
