- op: add
  path: /spec/egress/-
  value:
    ports:
      - port: 8080
        protocol: TCP
    to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: auth
        podSelector:
          matchLabels:
            app: mock-oauth2

