apiVersion: v1
kind: Namespace
metadata:
  name: lars
  labels:
    name: lars
    istio.io/rev: default
---
apiVersion: ztoperator.kartverket.no/v1alpha1
kind: AuthPolicy
metadata:
  name: test
  namespace: lars
spec:
  selector:
    matchLabels:
      app: an-application
  jwtRules:
    - enabled: true
      authRules:
        - paths:
            - /*
          when:
            - claim: "pid"
              values:
                - "*"
      secretName: "idporten-secret"
