apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: "ztoperator-system/webhook-cert"
webhooks:
  - name: vpod-v1.kb.io
    clientConfig:
      service:
        name: webhook-service
        namespace: ztoperator-system
    namespaceSelector:
      matchExpressions:
        - key: skip.kartverket.no/skip-managed
          operator: In
          values:
            - "true"
    matchConditions:
      - name: has-ztoperator-annotation-prefix
        expression: >
          object != null &&
          object.metadata != null &&
          ('annotations' in object.metadata) &&
          object.metadata.annotations.exists(k, k.startsWith("ztoperator.kartverket.no/"))
