apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: ztoperator-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: "ztoperator-system/webhook-cert"
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      url: https://host.docker.internal:9443/validate--v1-pod
    name: vpod-v1.kb.io
    failurePolicy: Fail
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
    namespaceSelector:
      matchExpressions:
        - key: skip.kartverket.no/skip-managed
          operator: In
          values:
            - "true"
    matchConditions:
      - name: has-ztoperator-annotation-prefix
        expression: >
          object != null &&
          object.metadata != null &&
          ('annotations' in object.metadata) &&
          object.metadata.annotations.exists(k, k.startsWith("ztoperator.kartverket.no/"))
